export const GARBAGE_TYPES = {
  automotive: 'types_automotive',
  glass: 'types_glass',
  electronics: 'types_electronics',
  metal: 'types_metal',
  plastic: 'types_plastic',
  household: 'types_household',
  hazardous: 'types_hazardous',
  construction: 'types_construction',
  paper: 'types_paper',
  clothing: 'types_clothing',
  batteries: 'types_batteries',
  lightBulbs: 'types_lightBulbs',
  organicWaste: 'types_organicWaste',
  other: 'types_other',
  tree: 'types_tree',
};
